apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: leader-elector 
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "create","delete", "patch", "update"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]

