apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: leader-elector
subjects:
- kind: ServiceAccount
  name: leader-elector # Name is case sensitive
  namespace: default
roleRef:
  kind: ClusterRole
  name: leader-elector
  apiGroup: rbac.authorization.k8s.io
